from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class IEventRepository(Protocol):
    async def events(self, offset: int, limit: int) -> list: ...

    async def detail(self, event_id: int): ...

    async def add(self, event: Any): ...


@runtime_checkable
class IApplicationRepository(Protocol):
    async def my_applications(self, user_id: int) -> list: ...

    async def add(self, application: Any) -> Any: ...

    async def delete(self, application: Any) -> None: ...

    async def count_by_event(self, event_id: int) -> int: ...

    async def get_by_user_and_event(self, user_id: int, event_id: int) -> Any: ...


@runtime_checkable
class IMinioImageStorage(Protocol):
    async def upload(self, file_obj, key: str) -> None: ...

    async def get_bytes(self, key: str) -> tuple[bytes, str]: ...

